name    'st01tkh-agwa-git-crypt'
version '0.1.0'
source 'https://github.com/st01tkh/puppet-st01tkh-agwa-git-crypt'
author 'st01tkh'
license 'Apache License, Version 2.0'
summary 'Setup AGWA git-crypt'
description 'Setup AGWA git-crypt'
project_page 'https://github.com/st01tkh/puppet-st01tkh-agwa-git-crypt'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'puppetlabs/apt', '>= 2.2.0'
dependency 'puppetlabs/git', '>= 0.4.0'
